"""Stable metadata contracts for RAG nodes.

Enterprise RAG systems should not pass loosely-shaped metadata dictionaries
between ingestion, retrieval, and UI layers. This module defines stable
contracts and builders used by the pipeline.
"""

from __future__ import annotations

import os
from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

ChunkRole = Literal["root", "parent", "leaf", "unknown"]
ChunkStrategy = Literal["hierarchical"]


class DocumentMetadata(BaseModel):
    """Document-level metadata produced by scanning and parsing."""

    doc_id: str = ""
    source_path: str = ""
    file_name: str = ""
    file_type: str = ""
    page_range: str = ""

    @classmethod
    def from_raw(cls, metadata: dict[str, Any], *, doc_id: str = "") -> "DocumentMetadata":
        source_path = _first_text(metadata, "source_path", "parent_source_path", "file_path")
        resolved_doc_id = doc_id or _first_text(metadata, "doc_id", "parent_doc_id")
        file_name = _first_text(metadata, "file_name", "filename")
        if not file_name and source_path:
            file_name = os.path.basename(source_path)
        if not file_name:
            file_name = resolved_doc_id or "unknown_file"

        return cls(
            doc_id=resolved_doc_id,
            source_path=source_path,
            file_name=file_name,
            file_type=_first_text(metadata, "file_type"),
            page_range=_first_text(metadata, "page_range", "parent_page_range"),
        )


class SectionMetadata(BaseModel):
    """Preprocessing section metadata.

    A section is an intermediate structure used for cleaning, audit, and source
    hints. It is not the same thing as a hierarchical parent chunk.
    """

    doc_id: str = ""
    source_path: str = ""
    section_id: str = ""
    section_index: int = 0
    section_title: str = ""
    section_path: str = ""
    page_range: str = ""
    block_count: int = 0

    @classmethod
    def from_raw(cls, metadata: dict[str, Any]) -> "SectionMetadata":
        section_title = _first_text(metadata, "section_title")
        return cls(
            doc_id=_first_text(metadata, "doc_id"),
            source_path=_first_text(metadata, "source_path"),
            section_id=_first_text(metadata, "section_id"),
            section_index=_safe_int(metadata.get("section_index")) or 0,
            section_title=section_title,
            section_path=_first_text(metadata, "section_path") or section_title,
            page_range=_first_text(metadata, "page_range"),
            block_count=_safe_int(metadata.get("block_count")) or 0,
        )


class HierarchyNodeMetadata(BaseModel):
    """Metadata for nodes generated by LlamaIndex HierarchicalNodeParser."""

    doc_id: str = ""
    source_path: str = ""
    file_name: str = ""
    file_type: str = ""
    page_range: str = ""
    chunk_strategy: ChunkStrategy = "hierarchical"
    chunk_role: ChunkRole = "unknown"
    hierarchy_node_id: str = ""
    chunk_id: str = ""
    parent_id: str = ""
    source_section_count: int = 0

    def to_storage_metadata(self) -> dict[str, Any]:
        """Full metadata for PostgreSQL/docstore."""

        return self.model_dump()

    def to_retrieval_metadata(self) -> dict[str, Any]:
        """Compact metadata for Milvus/BM25 retrieval."""

        return {
            "doc_id": self.doc_id,
            "source_path": self.source_path,
            "file_name": self.file_name,
            "file_type": self.file_type,
            "page_range": self.page_range,
            "chunk_strategy": self.chunk_strategy,
            "chunk_role": self.chunk_role,
            "hierarchy_node_id": self.hierarchy_node_id,
            "chunk_id": self.chunk_id,
            "parent_id": self.parent_id,
        }


def build_hierarchy_node_metadata(
    *,
    base_metadata: dict[str, Any],
    node_id: str,
    parent_id: str,
    role: ChunkRole,
    source_section_count: int = 0,
) -> dict[str, Any]:
    """Build standardized metadata for a hierarchical node."""

    doc_meta = DocumentMetadata.from_raw(base_metadata)
    result = HierarchyNodeMetadata(
        doc_id=doc_meta.doc_id,
        source_path=doc_meta.source_path,
        file_name=doc_meta.file_name,
        file_type=doc_meta.file_type,
        page_range=doc_meta.page_range,
        chunk_role=role,
        hierarchy_node_id=node_id,
        chunk_id=node_id,
        parent_id=parent_id,
        source_section_count=source_section_count,
    ).to_storage_metadata()
    
    if "paragraph_id" in base_metadata:
        result["paragraph_id"] = base_metadata["paragraph_id"]
    if "source" in base_metadata:
        result["source"] = base_metadata["source"]
    
    return result


class CanonicalChunkMetadata(BaseModel):
    """Canonical chunk metadata shared across storage and retrieval layers."""

    doc_id: str = ""
    file_name: str = ""
    source_path: str = ""
    file_type: str = ""
    chunk_id: str = ""
    chunk_role: ChunkRole = "unknown"
    parent_id: str = ""
    section_id: str = ""
    section_title: str = ""
    page_range: str = ""

    @classmethod
    def from_raw(cls, metadata: dict[str, Any]) -> "CanonicalChunkMetadata":
        source_path = _first_text(metadata, "source_path", "parent_source_path", "file_path")
        doc_id = _first_text(metadata, "doc_id", "parent_doc_id")
        file_name = _first_text(metadata, "file_name", "filename")
        if not file_name and source_path:
            file_name = os.path.basename(source_path)
        if not file_name:
            file_name = doc_id or "unknown_file"

        chunk_role = str(metadata.get("chunk_role") or "").strip()
        if chunk_role not in {"root", "parent", "leaf"}:
            chunk_role = "unknown"

        return cls(
            doc_id=doc_id,
            file_name=file_name,
            source_path=source_path,
            file_type=_first_text(metadata, "file_type"),
            chunk_id=_first_text(metadata, "chunk_id"),
            chunk_role=chunk_role,  # type: ignore[arg-type]
            parent_id=_first_text(metadata, "parent_id"),
            section_id=_first_text(metadata, "section_id", "parent_section_id"),
            section_title=_first_text(metadata, "section_title", "parent_section_title"),
            page_range=_first_text(metadata, "page_range", "parent_page_range"),
        )


class SourceNodePayload(BaseModel):
    """Stable source payload returned by API endpoints."""

    text: str = ""
    score: Optional[float] = None
    doc_id: str = ""
    file_name: str = "unknown_file"
    source_path: str = ""
    chunk_id: str = ""
    retrieval_mode: str = ""
    parent_id: str = ""
    parent_source_path: str = ""
    parent_section_title: str = ""
    parent_page_range: str = ""
    child_chunk_id: str = ""
    auto_merged: bool = False
    merge_ratio: Optional[float] = None
    merged_child_count: Optional[int] = None
    total_child_count: Optional[int] = None
    raw_metadata: dict[str, Any] = Field(default_factory=dict, exclude=True)

    @classmethod
    def from_node(cls, node: Any) -> "SourceNodePayload":
        metadata = dict(getattr(node, "metadata", {}) or {})
        canonical = CanonicalChunkMetadata.from_raw(metadata)

        source_path = canonical.source_path
        parent_source_path = _first_text(metadata, "parent_source_path") or source_path
        page_range = _first_text(metadata, "parent_page_range", "page_range")
        section_title = _first_text(metadata, "parent_section_title", "section_title")
        child_chunk_id = _first_text(metadata, "child_chunk_id", "chunk_id")

        return cls(
            text=str(getattr(node, "text", "") or ""),
            score=_safe_float(getattr(node, "score", None)),
            doc_id=canonical.doc_id,
            file_name=canonical.file_name,
            source_path=source_path,
            chunk_id=canonical.chunk_id,
            retrieval_mode=_first_text(metadata, "retrieval_mode", "chunk_role"),
            parent_id=canonical.parent_id,
            parent_source_path=parent_source_path,
            parent_section_title=section_title,
            parent_page_range=page_range,
            child_chunk_id=child_chunk_id,
            auto_merged=bool(metadata.get("auto_merged", False)),
            merge_ratio=_safe_float(metadata.get("merge_ratio")),
            merged_child_count=_safe_int(metadata.get("merged_child_count")),
            total_child_count=_safe_int(metadata.get("total_child_count")),
            raw_metadata=metadata,
        )

    def to_api_dict(self) -> dict[str, Any]:
        """Return a JSON-ready dict for FastAPI responses."""

        return self.model_dump(exclude={"raw_metadata"})


def build_parent_context_metadata(
    *,
    child_metadata: dict[str, Any],
    parent_row: dict[str, Any],
    child_text: str = "",
) -> dict[str, Any]:
    """Build metadata for parent-child expanded retrieval results."""

    child = CanonicalChunkMetadata.from_raw(child_metadata)
    parent_raw = dict(parent_row.get("metadata_json") or {})
    parent = CanonicalChunkMetadata.from_raw(
        {
            **parent_raw,
            "doc_id": parent_row.get("doc_id") or parent_raw.get("doc_id"),
            "source_path": parent_row.get("source_path") or parent_raw.get("source_path"),
            "chunk_id": parent_row.get("chunk_id") or parent_raw.get("chunk_id"),
            "parent_id": parent_row.get("parent_id") or parent_raw.get("parent_id"),
            "page_range": parent_row.get("page_range") or parent_raw.get("page_range"),
        }
    )

    return {
        **parent_raw,
        "retrieval_mode": "parent_child",
        "parent_lookup_status": "found",
        "doc_id": parent.doc_id or child.doc_id,
        "source_path": parent.source_path or child.source_path,
        "file_name": parent.file_name or child.file_name,
        "file_type": parent.file_type or child.file_type,
        "chunk_id": parent.chunk_id,
        "chunk_role": parent.chunk_role,
        "parent_id": parent.parent_id,
        "page_range": parent.page_range or child.page_range,
        "parent_doc_id": parent.doc_id or child.doc_id,
        "parent_source_path": parent.source_path or child.source_path,
        "parent_section_title": parent.section_title,
        "parent_page_range": parent.page_range or child.page_range,
        "child_chunk_id": child.chunk_id,
        "child_text_preview": child_text[:200],
    }


def build_auto_merged_metadata(
    *,
    parent_row: dict[str, Any],
    child_metadatas: list[dict[str, Any]],
    merge_threshold: float,
    total_child_count: int,
) -> dict[str, Any]:
    """Build metadata for AutoMerging retrieval results."""

    parent_raw = dict(parent_row.get("metadata_json") or {})
    parent = CanonicalChunkMetadata.from_raw(
        {
            **parent_raw,
            "doc_id": parent_row.get("doc_id") or parent_raw.get("doc_id"),
            "source_path": parent_row.get("source_path") or parent_raw.get("source_path"),
            "chunk_id": parent_row.get("chunk_id") or parent_raw.get("chunk_id"),
            "parent_id": parent_row.get("parent_id") or parent_raw.get("parent_id"),
            "page_range": parent_row.get("page_range") or parent_raw.get("page_range"),
        }
    )
    child_ids = [
        CanonicalChunkMetadata.from_raw(child_metadata).chunk_id
        for child_metadata in child_metadatas
    ]
    child_ids = [child_id for child_id in child_ids if child_id]
    merged_child_count = len(child_ids)

    return {
        **parent_raw,
        "retrieval_mode": "auto_merging",
        "auto_merged": True,
        "merge_threshold": merge_threshold,
        "merged_child_count": merged_child_count,
        "total_child_count": total_child_count,
        "merge_ratio": round(merged_child_count / total_child_count, 4) if total_child_count else 0,
        "merged_child_ids": child_ids,
        "doc_id": parent.doc_id,
        "source_path": parent.source_path,
        "file_name": parent.file_name,
        "file_type": parent.file_type,
        "chunk_id": parent.chunk_id,
        "chunk_role": parent.chunk_role,
        "parent_id": parent.parent_id,
        "page_range": parent.page_range,
        "parent_doc_id": parent.doc_id,
        "parent_source_path": parent.source_path,
        "parent_section_title": parent.section_title,
        "parent_page_range": parent.page_range,
        "child_chunk_id": child_ids[0] if child_ids else "",
    }


def _first_text(metadata: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = metadata.get(key)
        if value is None:
            continue
        text = str(value).strip()
        if text:
            return text
    return ""


def _safe_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _safe_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None
